### ISSUE TITLE
Cannot read property 'url_path' of null

### ISSUE THREAD

**Issue by vsychov** [strapi-community/strapi-plugin-url-alias#21]
### Describe the bug

Hello,

when some relations in database is broken, it's trigger an error:

```
[2022-09-13 11:50:45.360] error: Cannot read property 'url_path' of null
TypeError: Cannot read property 'url_path' of null
    at /srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/content-api/services/prepare-path.js:27:41
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 5)
    at async traverse (/srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/content-api/services/prepare-path.js:18:5)
    at async /srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/content-api/services/prepare-path.js:20:9
    at async Promise.all (index 12)
    at async Object.traverse [as preparePath] (/srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/content-api/services/prepare-path.js:18:5)
    at async Object.response (/srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/content-api/services/prepare-path.js:38:12)
    at async Object.findOne (/srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/admin-api/services/override-query-layer.js:18:24)
    at async Object.findOneWithCreatorRoles (/srv/app/node_modules/@strapi/plugin-content-manager/server/services/entity-manager.js:160:20)

```

### Steps to reproduce the behavior

1. Broke any relation to url_path

### Expected behavior

No exception, or foreign keys in database

**Comment by vsychov** [comment]
@boazpoolman,
1.0.0-alpha.6
4.3.8
postgres 13

**Comment by Alexnortung** [comment]
I have also experienced this issue. I am not 100% how to reproduce the bug, but if you define a pattern without locale and make two entries for that pattern and then change the pattern to also have locale. Then it seems like both entries have the same url alias id and I would have to delete one of the entries to get a new url alias for both entries.

**Comment by Alexnortung** [comment]
I think this has been resolved, please reopen if you are still experiencing the issue @vsychov
